"""Generate Rust/TypeScript protocol bindings from shared.protocol."""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from protocol import (
    AcroBikeSubstate,
    HopLandingParticleClass,
    BikeTransitionType,
    DebugTraversalAction,
    HeldButtons,
    PlayerAction,
    PROTOCOL_VERSION,
    Direction,
    MessageType,
    MovementMode,
    PlayerAvatar,
    RejectionReason,
    StepSpeed,
    TraversalState,
)

ROOT = Path(__file__).resolve().parents[1]
SERVER_OUT = ROOT / "server" / "src" / "protocol_generated.rs"
CLIENT_OUT = ROOT / "client" / "src" / "protocol_generated.ts"


def rust() -> str:
    return dedent(
        f"""// @generated by rebuild/shared/generate_protocol_bindings.py
use serde::{{Deserialize, Serialize}};

pub const PROTOCOL_VERSION: u16 = {PROTOCOL_VERSION};

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum MessageType {{
    JoinSession = 0x{int(MessageType.JOIN_SESSION):02x},
    WalkInput = 0x{int(MessageType.WALK_INPUT):02x},
    PlayerActionInput = 0x{int(MessageType.PLAYER_ACTION_INPUT):02x},
    DebugTraversalInput = 0x{int(MessageType.DEBUG_TRAVERSAL_INPUT):02x},
    HeldInputState = 0x{int(MessageType.HELD_INPUT_STATE):02x},
    SessionAccepted = 0x{int(MessageType.SESSION_ACCEPTED):02x},
    WorldSnapshot = 0x{int(MessageType.WORLD_SNAPSHOT):02x},
    WalkResult = 0x{int(MessageType.WALK_RESULT):02x},
    WorldDelta = 0x{int(MessageType.WORLD_DELTA):02x},
    BikeRuntimeDelta = 0x{int(MessageType.BIKE_RUNTIME_DELTA):02x},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Direction {{
    Up = {int(Direction.UP)},
    Down = {int(Direction.DOWN)},
    Left = {int(Direction.LEFT)},
    Right = {int(Direction.RIGHT)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MovementMode {{
    Walk = {int(MovementMode.WALK)},
    Run = {int(MovementMode.RUN)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StepSpeed {{
    Step1 = {int(StepSpeed.STEP1)},
    Step2 = {int(StepSpeed.STEP2)},
    Step3 = {int(StepSpeed.STEP3)},
    Step4 = {int(StepSpeed.STEP4)},
    Step8 = {int(StepSpeed.STEP8)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum HeldButtons {{
    None = {int(HeldButtons.NONE)},
    B = {int(HeldButtons.B)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum HeldDpad {{
    None = 0,
    Up = 1 << 0,
    Down = 1 << 1,
    Left = 1 << 2,
    Right = 1 << 3,
}}

pub fn sanitize_held_dpad_mask(mask: u8) -> u8 {{
    let mut sanitized = mask;
    let up_down = (HeldDpad::Up as u8) | (HeldDpad::Down as u8);
    let left_right = (HeldDpad::Left as u8) | (HeldDpad::Right as u8);
    if (sanitized & up_down) == up_down {{
        sanitized &= !up_down;
    }}
    if (sanitized & left_right) == left_right {{
        sanitized &= !left_right;
    }}
    sanitized
}}

pub fn resolve_direction_from_held_dpad(mask: u8) -> Option<Direction> {{
    let sanitized = sanitize_held_dpad_mask(mask);
    if (sanitized & HeldDpad::Up as u8) != 0 {{
        return Some(Direction::Up);
    }}
    if (sanitized & HeldDpad::Down as u8) != 0 {{
        return Some(Direction::Down);
    }}
    if (sanitized & HeldDpad::Left as u8) != 0 {{
        return Some(Direction::Left);
    }}
    if (sanitized & HeldDpad::Right as u8) != 0 {{
        return Some(Direction::Right);
    }}
    None
}}

pub fn direction_to_held_dpad_mask(direction: Direction) -> u8 {{
    match direction {{
        Direction::Up => HeldDpad::Up as u8,
        Direction::Down => HeldDpad::Down as u8,
        Direction::Left => HeldDpad::Left as u8,
        Direction::Right => HeldDpad::Right as u8,
    }}
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DebugTraversalAction {{
    ToggleMount = {int(DebugTraversalAction.TOGGLE_MOUNT)},
    SwapBikeType = {int(DebugTraversalAction.SWAP_BIKE_TYPE)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAction {{
    UseRegisteredBike = {int(PlayerAction.USE_REGISTERED_BIKE)},
    SwapBikeType = {int(PlayerAction.SWAP_BIKE_TYPE)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TraversalState {{
    OnFoot = {int(TraversalState.ON_FOOT)},
    MachBike = {int(TraversalState.MACH_BIKE)},
    AcroBike = {int(TraversalState.ACRO_BIKE)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AcroBikeSubstate {{
    None = {int(AcroBikeSubstate.NONE)},
    StandingWheelie = {int(AcroBikeSubstate.STANDING_WHEELIE)},
    MovingWheelie = {int(AcroBikeSubstate.MOVING_WHEELIE)},
    BunnyHop = {int(AcroBikeSubstate.BUNNY_HOP)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum BikeTransitionType {{
    None = {int(BikeTransitionType.NONE)},
    Mount = {int(BikeTransitionType.MOUNT)},
    Dismount = {int(BikeTransitionType.DISMOUNT)},
    EnterWheelie = {int(BikeTransitionType.ENTER_WHEELIE)},
    ExitWheelie = {int(BikeTransitionType.EXIT_WHEELIE)},
    Hop = {int(BikeTransitionType.HOP)},
    WheelieIdle = {int(BikeTransitionType.WHEELIE_IDLE)},
    WheeliePop = {int(BikeTransitionType.WHEELIE_POP)},
    WheelieEnd = {int(BikeTransitionType.WHEELIE_END)},
    HopStanding = {int(BikeTransitionType.HOP_STANDING)},
    HopMoving = {int(BikeTransitionType.HOP_MOVING)},
    SideJump = {int(BikeTransitionType.SIDE_JUMP)},
    TurnJump = {int(BikeTransitionType.TURN_JUMP)},
    NormalToWheelie = {int(BikeTransitionType.NORMAL_TO_WHEELIE)},
    WheelieToNormal = {int(BikeTransitionType.WHEELIE_TO_NORMAL)},
    WheelieHoppingStanding = {int(BikeTransitionType.WHEELIE_HOPPING_STANDING)},
    WheelieHoppingMoving = {int(BikeTransitionType.WHEELIE_HOPPING_MOVING)},
    WheelieMoving = {int(BikeTransitionType.WHEELIE_MOVING)},
    WheelieRisingMoving = {int(BikeTransitionType.WHEELIE_RISING_MOVING)},
    WheelieLoweringMoving = {int(BikeTransitionType.WHEELIE_LOWERING_MOVING)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HopLandingParticleClass {{
    NormalGroundDust = {int(HopLandingParticleClass.NORMAL_GROUND_DUST)},
    TallGrassJump = {int(HopLandingParticleClass.TALL_GRASS_JUMP)},
    LongGrassJump = {int(HopLandingParticleClass.LONG_GRASS_JUMP)},
    ShallowWaterSplash = {int(HopLandingParticleClass.SHALLOW_WATER_SPLASH)},
    DeepWaterSplash = {int(HopLandingParticleClass.DEEP_WATER_SPLASH)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectionReason {{
    None = {int(RejectionReason.NONE)},
    Collision = {int(RejectionReason.COLLISION)},
    OutOfBounds = {int(RejectionReason.OUT_OF_BOUNDS)},
    SequenceMismatch = {int(RejectionReason.SEQUENCE_MISMATCH)},
    NotJoined = {int(RejectionReason.NOT_JOINED)},
    InvalidDirection = {int(RejectionReason.INVALID_DIRECTION)},
    ForcedMovementDisabled = {int(RejectionReason.FORCED_MOVEMENT_DISABLED)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAvatar {{
    Brendan = {int(PlayerAvatar.BRENDAN)},
    May = {int(PlayerAvatar.MAY)},
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct Position {{
    pub x: u16,
    pub y: u16,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct JoinSession {{
    pub player_id: String,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkInput {{
    pub direction: Direction,
    pub movement_mode: MovementMode,
    pub held_buttons: u8,
    pub input_seq: u32,
    pub client_time: u64,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct HeldInputState {{
    pub held_dpad: u8,
    pub held_buttons: u8,
    pub input_seq: u32,
    pub client_time: u64,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct DebugTraversalInput {{
    pub action: DebugTraversalAction,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct PlayerActionInput {{
    pub action: PlayerAction,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct SessionAccepted {{
    pub session_id: u32,
    pub server_frame: u32,
    pub avatar: PlayerAvatar,
    pub asset_base_url: String,
    pub asset_version: String,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldSnapshot {{
    pub map_id: u16,
    pub player_pos: Position,
    pub facing: Direction,
    pub avatar: PlayerAvatar,
    pub map_chunk_hash: Vec<u8>,
    pub map_chunk: Vec<u8>,
    pub server_frame: u32,
    pub traversal_state: TraversalState,
    pub preferred_bike_type: TraversalState,
    pub player_elevation: u8,
    pub authoritative_step_speed: Option<StepSpeed>,
    pub mach_speed_stage: Option<u8>,
    pub acro_substate: Option<AcroBikeSubstate>,
    pub bike_transition: Option<BikeTransitionType>,
    pub bunny_hop_cycle_tick: Option<u8>,
    pub bike_effect_flags: u8,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkResult {{
    pub input_seq: u32,
    pub accepted: bool,
    pub authoritative_pos: Position,
    pub facing: Direction,
    pub reason: RejectionReason,
    pub server_frame: u32,
    pub traversal_state: TraversalState,
    pub preferred_bike_type: TraversalState,
    pub player_elevation: u8,
    pub authoritative_step_speed: Option<StepSpeed>,
    pub mach_speed_stage: Option<u8>,
    pub acro_substate: Option<AcroBikeSubstate>,
    pub bike_transition: Option<BikeTransitionType>,
    pub bike_effect_flags: u8,
    pub bunny_hop_cycle_tick: Option<u8>,
    pub hop_landing_particle_class: Option<HopLandingParticleClass>,
    pub hop_landing_tile_x: Option<u16>,
    pub hop_landing_tile_y: Option<u16>,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldDelta {{
    pub map_id: u16,
    pub server_frame: u32,
    pub delta_blob: Vec<u8>,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct BikeRuntimeDelta {{
    pub server_frame: u32,
    pub traversal_state: TraversalState,
    pub player_elevation: u8,
    pub facing: Direction,
    pub authoritative_step_speed: Option<StepSpeed>,
    pub mach_speed_stage: Option<u8>,
    pub acro_substate: Option<AcroBikeSubstate>,
    pub bike_transition: Option<BikeTransitionType>,
    pub bunny_hop_cycle_tick: Option<u8>,
    pub hop_landing_particle_class: Option<HopLandingParticleClass>,
    pub hop_landing_tile_x: Option<u16>,
    pub hop_landing_tile_y: Option<u16>,
}}
"""
    )


def ts() -> str:
    return dedent(
        f"""// @generated by rebuild/shared/generate_protocol_bindings.py
export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;

export enum MessageType {{
  JOIN_SESSION = 0x{int(MessageType.JOIN_SESSION):02x},
  WALK_INPUT = 0x{int(MessageType.WALK_INPUT):02x},
  PLAYER_ACTION_INPUT = 0x{int(MessageType.PLAYER_ACTION_INPUT):02x},
  DEBUG_TRAVERSAL_INPUT = 0x{int(MessageType.DEBUG_TRAVERSAL_INPUT):02x},
  HELD_INPUT_STATE = 0x{int(MessageType.HELD_INPUT_STATE):02x},
  SESSION_ACCEPTED = 0x{int(MessageType.SESSION_ACCEPTED):02x},
  WORLD_SNAPSHOT = 0x{int(MessageType.WORLD_SNAPSHOT):02x},
  WALK_RESULT = 0x{int(MessageType.WALK_RESULT):02x},
  WORLD_DELTA = 0x{int(MessageType.WORLD_DELTA):02x},
  BIKE_RUNTIME_DELTA = 0x{int(MessageType.BIKE_RUNTIME_DELTA):02x},
}}

export enum Direction {{
  UP = {int(Direction.UP)},
  DOWN = {int(Direction.DOWN)},
  LEFT = {int(Direction.LEFT)},
  RIGHT = {int(Direction.RIGHT)},
}}

export enum MovementMode {{
  WALK = {int(MovementMode.WALK)},
  RUN = {int(MovementMode.RUN)},
}}

export enum StepSpeed {{
  STEP1 = {int(StepSpeed.STEP1)},
  STEP2 = {int(StepSpeed.STEP2)},
  STEP3 = {int(StepSpeed.STEP3)},
  STEP4 = {int(StepSpeed.STEP4)},
  STEP8 = {int(StepSpeed.STEP8)},
}}

export enum HeldButtons {{
  NONE = {int(HeldButtons.NONE)},
  B = {int(HeldButtons.B)},
}}

export enum HeldDpad {{
  NONE = 0,
  UP = 1 << 0,
  DOWN = 1 << 1,
  LEFT = 1 << 2,
  RIGHT = 1 << 3,
}}

export function sanitizeHeldDpadMask(mask: number): number {{
  let sanitized = mask;
  const upDown = HeldDpad.UP | HeldDpad.DOWN;
  const leftRight = HeldDpad.LEFT | HeldDpad.RIGHT;
  if ((sanitized & upDown) === upDown) {{
    sanitized &= ~upDown;
  }}
  if ((sanitized & leftRight) === leftRight) {{
    sanitized &= ~leftRight;
  }}
  return sanitized;
}}

export function resolveDirectionFromHeldDpad(mask: number): Direction | undefined {{
  const sanitized = sanitizeHeldDpadMask(mask);
  if ((sanitized & HeldDpad.UP) !== 0) {{
    return Direction.UP;
  }}
  if ((sanitized & HeldDpad.DOWN) !== 0) {{
    return Direction.DOWN;
  }}
  if ((sanitized & HeldDpad.LEFT) !== 0) {{
    return Direction.LEFT;
  }}
  if ((sanitized & HeldDpad.RIGHT) !== 0) {{
    return Direction.RIGHT;
  }}
  return undefined;
}}

export function directionToHeldDpadMask(direction: Direction): number {{
  switch (direction) {{
    case Direction.UP:
      return HeldDpad.UP;
    case Direction.DOWN:
      return HeldDpad.DOWN;
    case Direction.LEFT:
      return HeldDpad.LEFT;
    case Direction.RIGHT:
      return HeldDpad.RIGHT;
    default:
      return HeldDpad.NONE;
  }}
}}

export enum DebugTraversalAction {{
  TOGGLE_MOUNT = {int(DebugTraversalAction.TOGGLE_MOUNT)},
  SWAP_BIKE_TYPE = {int(DebugTraversalAction.SWAP_BIKE_TYPE)},
}}

export enum PlayerAction {{
  USE_REGISTERED_BIKE = {int(PlayerAction.USE_REGISTERED_BIKE)},
  SWAP_BIKE_TYPE = {int(PlayerAction.SWAP_BIKE_TYPE)},
}}

export enum TraversalState {{
  ON_FOOT = {int(TraversalState.ON_FOOT)},
  MACH_BIKE = {int(TraversalState.MACH_BIKE)},
  ACRO_BIKE = {int(TraversalState.ACRO_BIKE)},
}}

export enum AcroBikeSubstate {{
  NONE = {int(AcroBikeSubstate.NONE)},
  STANDING_WHEELIE = {int(AcroBikeSubstate.STANDING_WHEELIE)},
  MOVING_WHEELIE = {int(AcroBikeSubstate.MOVING_WHEELIE)},
  BUNNY_HOP = {int(AcroBikeSubstate.BUNNY_HOP)},
}}

export enum BikeTransitionType {{
  NONE = {int(BikeTransitionType.NONE)},
  MOUNT = {int(BikeTransitionType.MOUNT)},
  DISMOUNT = {int(BikeTransitionType.DISMOUNT)},
  ENTER_WHEELIE = {int(BikeTransitionType.ENTER_WHEELIE)},
  EXIT_WHEELIE = {int(BikeTransitionType.EXIT_WHEELIE)},
  HOP = {int(BikeTransitionType.HOP)},
  WHEELIE_IDLE = {int(BikeTransitionType.WHEELIE_IDLE)},
  WHEELIE_POP = {int(BikeTransitionType.WHEELIE_POP)},
  WHEELIE_END = {int(BikeTransitionType.WHEELIE_END)},
  HOP_STANDING = {int(BikeTransitionType.HOP_STANDING)},
  HOP_MOVING = {int(BikeTransitionType.HOP_MOVING)},
  SIDE_JUMP = {int(BikeTransitionType.SIDE_JUMP)},
  TURN_JUMP = {int(BikeTransitionType.TURN_JUMP)},
  NORMAL_TO_WHEELIE = {int(BikeTransitionType.NORMAL_TO_WHEELIE)},
  WHEELIE_TO_NORMAL = {int(BikeTransitionType.WHEELIE_TO_NORMAL)},
  WHEELIE_HOPPING_STANDING = {int(BikeTransitionType.WHEELIE_HOPPING_STANDING)},
  WHEELIE_HOPPING_MOVING = {int(BikeTransitionType.WHEELIE_HOPPING_MOVING)},
  WHEELIE_MOVING = {int(BikeTransitionType.WHEELIE_MOVING)},
  WHEELIE_RISING_MOVING = {int(BikeTransitionType.WHEELIE_RISING_MOVING)},
  WHEELIE_LOWERING_MOVING = {int(BikeTransitionType.WHEELIE_LOWERING_MOVING)},
}}

export enum HopLandingParticleClass {{
  NORMAL_GROUND_DUST = {int(HopLandingParticleClass.NORMAL_GROUND_DUST)},
  TALL_GRASS_JUMP = {int(HopLandingParticleClass.TALL_GRASS_JUMP)},
  LONG_GRASS_JUMP = {int(HopLandingParticleClass.LONG_GRASS_JUMP)},
  SHALLOW_WATER_SPLASH = {int(HopLandingParticleClass.SHALLOW_WATER_SPLASH)},
  DEEP_WATER_SPLASH = {int(HopLandingParticleClass.DEEP_WATER_SPLASH)},
}}

export enum RejectionReason {{
  NONE = {int(RejectionReason.NONE)},
  COLLISION = {int(RejectionReason.COLLISION)},
  OUT_OF_BOUNDS = {int(RejectionReason.OUT_OF_BOUNDS)},
  SEQUENCE_MISMATCH = {int(RejectionReason.SEQUENCE_MISMATCH)},
  NOT_JOINED = {int(RejectionReason.NOT_JOINED)},
  INVALID_DIRECTION = {int(RejectionReason.INVALID_DIRECTION)},
  FORCED_MOVEMENT_DISABLED = {int(RejectionReason.FORCED_MOVEMENT_DISABLED)},
}}

export enum PlayerAvatar {{
  BRENDAN = {int(PlayerAvatar.BRENDAN)},
  MAY = {int(PlayerAvatar.MAY)},
}}

export type Position = {{ x: number; y: number }};
export type JoinSession = {{ player_id: string }};
export type WalkInput = {{
  direction: Direction;
  movement_mode: MovementMode;
  held_buttons: number;
  input_seq: number;
  client_time: bigint;
}};
export type HeldInputState = {{
  held_dpad: number;
  held_buttons: number;
  input_seq: number;
  client_time: bigint;
}};
export type DebugTraversalInput = {{
  action: DebugTraversalAction;
}};
export type PlayerActionInput = {{
  action: PlayerAction;
}};
export type SessionAccepted = {{
  session_id: number;
  server_frame: number;
  avatar: PlayerAvatar;
  asset_base_url: string;
  asset_version: string;
}};
export type WorldSnapshot = {{
  map_id: number;
  player_pos: Position;
  facing: Direction;
  avatar: PlayerAvatar;
  map_chunk_hash: Uint8Array;
  map_chunk: Uint8Array;
  server_frame: number;
  traversal_state: TraversalState;
  preferred_bike_type: TraversalState;
  player_elevation: number;
  authoritative_step_speed?: StepSpeed;
  mach_speed_stage?: number;
  acro_substate?: AcroBikeSubstate;
  bike_transition?: BikeTransitionType;
  bunny_hop_cycle_tick?: number;
  bike_effect_flags: number;
}};
export type WalkResult = {{
  input_seq: number;
  accepted: boolean;
  authoritative_pos: Position;
  facing: Direction;
  reason: RejectionReason;
  server_frame: number;
  traversal_state: TraversalState;
  preferred_bike_type: TraversalState;
  player_elevation: number;
  authoritative_step_speed?: StepSpeed;
  mach_speed_stage?: number;
  acro_substate?: AcroBikeSubstate;
  bike_transition?: BikeTransitionType;
  bike_effect_flags: number;
  bunny_hop_cycle_tick?: number;
  hop_landing_particle_class?: HopLandingParticleClass;
  hop_landing_tile_x?: number;
  hop_landing_tile_y?: number;
}};
export type WorldDelta = {{ map_id: number; server_frame: number; delta_blob: Uint8Array }};
export type BikeRuntimeDelta = {{
  server_frame: number;
  traversal_state: TraversalState;
  player_elevation: number;
  facing: Direction;
  authoritative_step_speed?: StepSpeed;
  mach_speed_stage?: number;
  acro_substate?: AcroBikeSubstate;
  bike_transition?: BikeTransitionType;
  bunny_hop_cycle_tick?: number;
  hop_landing_particle_class?: HopLandingParticleClass;
  hop_landing_tile_x?: number;
  hop_landing_tile_y?: number;
}};
"""
    )


if __name__ == "__main__":
    SERVER_OUT.write_text(rust())
    CLIENT_OUT.write_text(ts())
    print(f"wrote {SERVER_OUT}")
    print(f"wrote {CLIENT_OUT}")
