"""Generate Rust/TypeScript protocol bindings from shared.protocol."""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from protocol import (
    PROTOCOL_VERSION,
    Direction,
    MessageType,
    MovementMode,
    PlayerAvatar,
    RejectionReason,
)

ROOT = Path(__file__).resolve().parents[1]
SERVER_OUT = ROOT / "server" / "src" / "protocol_generated.rs"
CLIENT_OUT = ROOT / "client" / "src" / "protocol_generated.ts"


def rust() -> str:
    return dedent(
        f"""// @generated by rebuild/shared/generate_protocol_bindings.py
use serde::{{Deserialize, Serialize}};

pub const PROTOCOL_VERSION: u16 = {PROTOCOL_VERSION};

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum MessageType {{
    JoinSession = 0x{int(MessageType.JOIN_SESSION):02x},
    WalkInput = 0x{int(MessageType.WALK_INPUT):02x},
    SessionAccepted = 0x{int(MessageType.SESSION_ACCEPTED):02x},
    WorldSnapshot = 0x{int(MessageType.WORLD_SNAPSHOT):02x},
    WalkResult = 0x{int(MessageType.WALK_RESULT):02x},
    WorldDelta = 0x{int(MessageType.WORLD_DELTA):02x},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Direction {{
    Up = {int(Direction.UP)},
    Down = {int(Direction.DOWN)},
    Left = {int(Direction.LEFT)},
    Right = {int(Direction.RIGHT)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MovementMode {{
    Walk = {int(MovementMode.WALK)},
    Run = {int(MovementMode.RUN)},
    MachBike = {int(MovementMode.MACH_BIKE)},
    AcroCruise = {int(MovementMode.ACRO_CRUISE)},
    AcroWheeliePrep = {int(MovementMode.ACRO_WHEELIE_PREP)},
    AcroWheelieMove = {int(MovementMode.ACRO_WHEELIE_MOVE)},
    BunnyHop = {int(MovementMode.BUNNY_HOP)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectionReason {{
    None = {int(RejectionReason.NONE)},
    Collision = {int(RejectionReason.COLLISION)},
    OutOfBounds = {int(RejectionReason.OUT_OF_BOUNDS)},
    SequenceMismatch = {int(RejectionReason.SEQUENCE_MISMATCH)},
    NotJoined = {int(RejectionReason.NOT_JOINED)},
    InvalidDirection = {int(RejectionReason.INVALID_DIRECTION)},
    ForcedMovementDisabled = {int(RejectionReason.FORCED_MOVEMENT_DISABLED)},
    BikeInvalidStateTransition = {int(RejectionReason.BIKE_INVALID_STATE_TRANSITION)},
    BikeTurnTooSharp = {int(RejectionReason.BIKE_TURN_TOO_SHARP)},
    BikeWheelieWindowExpired = {int(RejectionReason.BIKE_WHEELIE_WINDOW_EXPIRED)},
    BikeTileRequiresMach = {int(RejectionReason.BIKE_TILE_REQUIRES_MACH)},
}}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAvatar {{
    Brendan = {int(PlayerAvatar.BRENDAN)},
    May = {int(PlayerAvatar.MAY)},
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct Position {{
    pub x: u16,
    pub y: u16,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct JoinSession {{
    pub player_id: String,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkInput {{
    pub direction: Direction,
    pub movement_mode: MovementMode,
    pub input_seq: u32,
    pub client_time: u64,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct SessionAccepted {{
    pub session_id: u32,
    pub server_frame: u32,
    pub avatar: PlayerAvatar,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldSnapshot {{
    pub map_id: u16,
    pub player_pos: Position,
    pub facing: Direction,
    pub avatar: PlayerAvatar,
    pub map_chunk_hash: Vec<u8>,
    pub map_chunk: Vec<u8>,
    pub server_frame: u32,
}}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkResult {{
    pub input_seq: u32,
    pub accepted: bool,
    pub authoritative_pos: Position,
    pub facing: Direction,
    pub reason: RejectionReason,
    pub server_frame: u32,
}}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldDelta {{
    pub map_id: u16,
    pub server_frame: u32,
    pub delta_blob: Vec<u8>,
}}
"""
    )


def ts() -> str:
    return dedent(
        f"""// @generated by rebuild/shared/generate_protocol_bindings.py
export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;

export enum MessageType {{
  JOIN_SESSION = 0x{int(MessageType.JOIN_SESSION):02x},
  WALK_INPUT = 0x{int(MessageType.WALK_INPUT):02x},
  SESSION_ACCEPTED = 0x{int(MessageType.SESSION_ACCEPTED):02x},
  WORLD_SNAPSHOT = 0x{int(MessageType.WORLD_SNAPSHOT):02x},
  WALK_RESULT = 0x{int(MessageType.WALK_RESULT):02x},
  WORLD_DELTA = 0x{int(MessageType.WORLD_DELTA):02x},
}}

export enum Direction {{
  UP = {int(Direction.UP)},
  DOWN = {int(Direction.DOWN)},
  LEFT = {int(Direction.LEFT)},
  RIGHT = {int(Direction.RIGHT)},
}}

export enum MovementMode {{
  WALK = {int(MovementMode.WALK)},
  RUN = {int(MovementMode.RUN)},
  MACH_BIKE = {int(MovementMode.MACH_BIKE)},
  ACRO_CRUISE = {int(MovementMode.ACRO_CRUISE)},
  ACRO_WHEELIE_PREP = {int(MovementMode.ACRO_WHEELIE_PREP)},
  ACRO_WHEELIE_MOVE = {int(MovementMode.ACRO_WHEELIE_MOVE)},
  BUNNY_HOP = {int(MovementMode.BUNNY_HOP)},
}}

export enum RejectionReason {{
  NONE = {int(RejectionReason.NONE)},
  COLLISION = {int(RejectionReason.COLLISION)},
  OUT_OF_BOUNDS = {int(RejectionReason.OUT_OF_BOUNDS)},
  SEQUENCE_MISMATCH = {int(RejectionReason.SEQUENCE_MISMATCH)},
  NOT_JOINED = {int(RejectionReason.NOT_JOINED)},
  INVALID_DIRECTION = {int(RejectionReason.INVALID_DIRECTION)},
  FORCED_MOVEMENT_DISABLED = {int(RejectionReason.FORCED_MOVEMENT_DISABLED)},
  BIKE_INVALID_STATE_TRANSITION = {int(RejectionReason.BIKE_INVALID_STATE_TRANSITION)},
  BIKE_TURN_TOO_SHARP = {int(RejectionReason.BIKE_TURN_TOO_SHARP)},
  BIKE_WHEELIE_WINDOW_EXPIRED = {int(RejectionReason.BIKE_WHEELIE_WINDOW_EXPIRED)},
  BIKE_TILE_REQUIRES_MACH = {int(RejectionReason.BIKE_TILE_REQUIRES_MACH)},
}}

export enum PlayerAvatar {{
  BRENDAN = {int(PlayerAvatar.BRENDAN)},
  MAY = {int(PlayerAvatar.MAY)},
}}

export type Position = {{ x: number; y: number }};
export type JoinSession = {{ player_id: string }};
export type WalkInput = {{
  direction: Direction;
  movement_mode: MovementMode;
  input_seq: number;
  client_time: bigint;
}};
export type SessionAccepted = {{ session_id: number; server_frame: number; avatar: PlayerAvatar }};
export type WorldSnapshot = {{
  map_id: number;
  player_pos: Position;
  facing: Direction;
  avatar: PlayerAvatar;
  map_chunk_hash: Uint8Array;
  map_chunk: Uint8Array;
  server_frame: number;
}};
export type WalkResult = {{
  input_seq: number;
  accepted: boolean;
  authoritative_pos: Position;
  facing: Direction;
  reason: RejectionReason;
  server_frame: number;
}};
export type WorldDelta = {{ map_id: number; server_frame: number; delta_blob: Uint8Array }};
"""
    )


if __name__ == "__main__":
    SERVER_OUT.write_text(rust())
    CLIENT_OUT.write_text(ts())
    print(f"wrote {SERVER_OUT}")
    print(f"wrote {CLIENT_OUT}")
