// @generated by rebuild/shared/generate_protocol_bindings.py
use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u16 = 9;

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum MessageType {
    JoinSession = 0x01,
    WalkInput = 0x02,
    PlayerActionInput = 0x03,
    DebugTraversalInput = 0x04,
    HeldInputState = 0x05,
    SessionAccepted = 0x81,
    WorldSnapshot = 0x82,
    WalkResult = 0x83,
    WorldDelta = 0x84,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Direction {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MovementMode {
    Walk = 0,
    Run = 1,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StepSpeed {
    Step1 = 0,
    Step2 = 1,
    Step3 = 2,
    Step4 = 3,
    Step8 = 4,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum HeldButtons {
    None = 0,
    B = 1,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DebugTraversalAction {
    ToggleMount = 0,
    SwapBikeType = 1,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAction {
    UseRegisteredBike = 0,
    SwapBikeType = 1,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TraversalState {
    OnFoot = 0,
    MachBike = 1,
    AcroBike = 2,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AcroBikeSubstate {
    None = 0,
    StandingWheelie = 1,
    MovingWheelie = 2,
    BunnyHop = 3,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum BikeTransitionType {
    None = 0,
    Mount = 1,
    Dismount = 2,
    EnterWheelie = 3,
    ExitWheelie = 4,
    Hop = 5,
    WheelieIdle = 6,
    WheeliePop = 7,
    WheelieEnd = 8,
    HopStanding = 9,
    HopMoving = 10,
    SideJump = 11,
    TurnJump = 12,
    NormalToWheelie = 13,
    WheelieToNormal = 14,
    WheelieHoppingStanding = 15,
    WheelieHoppingMoving = 16,
    WheelieMoving = 17,
    WheelieRisingMoving = 18,
    WheelieLoweringMoving = 19,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectionReason {
    None = 0,
    Collision = 1,
    OutOfBounds = 2,
    SequenceMismatch = 3,
    NotJoined = 4,
    InvalidDirection = 5,
    ForcedMovementDisabled = 6,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAvatar {
    Brendan = 0,
    May = 1,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct Position {
    pub x: u16,
    pub y: u16,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct JoinSession {
    pub player_id: String,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkInput {
    pub direction: Direction,
    pub movement_mode: MovementMode,
    pub held_buttons: u8,
    pub input_seq: u32,
    pub client_time: u64,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct HeldInputState {
    pub held_direction: Option<Direction>,
    pub held_buttons: u8,
    pub input_seq: u32,
    pub client_time: u64,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct DebugTraversalInput {
    pub action: DebugTraversalAction,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct PlayerActionInput {
    pub action: PlayerAction,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct SessionAccepted {
    pub session_id: u32,
    pub server_frame: u32,
    pub avatar: PlayerAvatar,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldSnapshot {
    pub map_id: u16,
    pub player_pos: Position,
    pub facing: Direction,
    pub avatar: PlayerAvatar,
    pub map_chunk_hash: Vec<u8>,
    pub map_chunk: Vec<u8>,
    pub server_frame: u32,
    pub traversal_state: TraversalState,
    pub preferred_bike_type: TraversalState,
    pub authoritative_step_speed: Option<StepSpeed>,
    pub mach_speed_stage: Option<u8>,
    pub acro_substate: Option<AcroBikeSubstate>,
    pub bike_transition: Option<BikeTransitionType>,
    pub bike_effect_flags: u8,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkResult {
    pub input_seq: u32,
    pub accepted: bool,
    pub authoritative_pos: Position,
    pub facing: Direction,
    pub reason: RejectionReason,
    pub server_frame: u32,
    pub traversal_state: TraversalState,
    pub preferred_bike_type: TraversalState,
    pub authoritative_step_speed: Option<StepSpeed>,
    pub mach_speed_stage: Option<u8>,
    pub acro_substate: Option<AcroBikeSubstate>,
    pub bike_transition: Option<BikeTransitionType>,
    pub bike_effect_flags: u8,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldDelta {
    pub map_id: u16,
    pub server_frame: u32,
    pub delta_blob: Vec<u8>,
}
