// @generated by rebuild/shared/generate_protocol_bindings.py
use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u16 = 2;

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum MessageType {
    JoinSession = 0x01,
    WalkInput = 0x02,
    SessionAccepted = 0x81,
    WorldSnapshot = 0x82,
    WalkResult = 0x83,
    WorldDelta = 0x84,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Direction {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MovementMode {
    Walk = 0,
    Run = 1,
    MachBike = 2,
    AcroCruise = 3,
    AcroWheeliePrep = 4,
    AcroWheelieMove = 5,
    BunnyHop = 6,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectionReason {
    None = 0,
    Collision = 1,
    OutOfBounds = 2,
    SequenceMismatch = 3,
    NotJoined = 4,
    InvalidDirection = 5,
    ForcedMovementDisabled = 6,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PlayerAvatar {
    Brendan = 0,
    May = 1,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct Position {
    pub x: u16,
    pub y: u16,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct JoinSession {
    pub player_id: String,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkInput {
    pub direction: Direction,
    pub movement_mode: MovementMode,
    pub input_seq: u32,
    pub client_time: u64,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct SessionAccepted {
    pub session_id: u32,
    pub server_frame: u32,
    pub avatar: PlayerAvatar,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldSnapshot {
    pub map_id: u16,
    pub player_pos: Position,
    pub facing: Direction,
    pub avatar: PlayerAvatar,
    pub map_chunk_hash: Vec<u8>,
    pub map_chunk: Vec<u8>,
    pub server_frame: u32,
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub struct WalkResult {
    pub input_seq: u32,
    pub accepted: bool,
    pub authoritative_pos: Position,
    pub facing: Direction,
    pub reason: RejectionReason,
    pub server_frame: u32,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct WorldDelta {
    pub map_id: u16,
    pub server_frame: u32,
    pub delta_blob: Vec<u8>,
}
