// @generated by rebuild/shared/generate_protocol_bindings.py
export const PROTOCOL_VERSION = 2 as const;

export enum MessageType {
  JOIN_SESSION = 0x01,
  WALK_INPUT = 0x02,
  SESSION_ACCEPTED = 0x81,
  WORLD_SNAPSHOT = 0x82,
  WALK_RESULT = 0x83,
  WORLD_DELTA = 0x84,
}

export enum Direction {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
}

export enum MovementMode {
  WALK = 0,
  RUN = 1,
  MACH_BIKE = 2,
  ACRO_CRUISE = 3,
  ACRO_WHEELIE_PREP = 4,
  ACRO_WHEELIE_MOVE = 5,
  BUNNY_HOP = 6,
}

export enum RejectionReason {
  NONE = 0,
  COLLISION = 1,
  OUT_OF_BOUNDS = 2,
  SEQUENCE_MISMATCH = 3,
  NOT_JOINED = 4,
  INVALID_DIRECTION = 5,
  FORCED_MOVEMENT_DISABLED = 6,
  BIKE_INVALID_STATE_TRANSITION = 7,
  BIKE_TURN_TOO_SHARP = 8,
  BIKE_WHEELIE_WINDOW_EXPIRED = 9,
  BIKE_TILE_REQUIRES_MACH = 10,
}

export enum PlayerAvatar {
  BRENDAN = 0,
  MAY = 1,
}

export type Position = { x: number; y: number };
export type JoinSession = { player_id: string };
export type WalkInput = {
  direction: Direction;
  movement_mode: MovementMode;
  input_seq: number;
  client_time: bigint;
};
export type SessionAccepted = { session_id: number; server_frame: number; avatar: PlayerAvatar };
export type WorldSnapshot = {
  map_id: number;
  player_pos: Position;
  facing: Direction;
  avatar: PlayerAvatar;
  map_chunk_hash: Uint8Array;
  map_chunk: Uint8Array;
  server_frame: number;
};
export type WalkResult = {
  input_seq: number;
  accepted: boolean;
  authoritative_pos: Position;
  facing: Direction;
  reason: RejectionReason;
  server_frame: number;
};
export type WorldDelta = { map_id: number; server_frame: number; delta_blob: Uint8Array };
