// @generated by rebuild/shared/generate_protocol_bindings.py
export const PROTOCOL_VERSION = 9 as const;

export enum MessageType {
  JOIN_SESSION = 0x01,
  WALK_INPUT = 0x02,
  PLAYER_ACTION_INPUT = 0x03,
  DEBUG_TRAVERSAL_INPUT = 0x04,
  HELD_INPUT_STATE = 0x05,
  SESSION_ACCEPTED = 0x81,
  WORLD_SNAPSHOT = 0x82,
  WALK_RESULT = 0x83,
  WORLD_DELTA = 0x84,
}

export enum Direction {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
}

export enum MovementMode {
  WALK = 0,
  RUN = 1,
}

export enum StepSpeed {
  STEP1 = 0,
  STEP2 = 1,
  STEP3 = 2,
  STEP4 = 3,
  STEP8 = 4,
}

export enum HeldButtons {
  NONE = 0,
  B = 1,
}

export enum DebugTraversalAction {
  TOGGLE_MOUNT = 0,
  SWAP_BIKE_TYPE = 1,
}

export enum PlayerAction {
  USE_REGISTERED_BIKE = 0,
  SWAP_BIKE_TYPE = 1,
}

export enum TraversalState {
  ON_FOOT = 0,
  MACH_BIKE = 1,
  ACRO_BIKE = 2,
}

export enum AcroBikeSubstate {
  NONE = 0,
  STANDING_WHEELIE = 1,
  MOVING_WHEELIE = 2,
  BUNNY_HOP = 3,
}

export enum BikeTransitionType {
  NONE = 0,
  MOUNT = 1,
  DISMOUNT = 2,
  ENTER_WHEELIE = 3,
  EXIT_WHEELIE = 4,
  HOP = 5,
  WHEELIE_IDLE = 6,
  WHEELIE_POP = 7,
  WHEELIE_END = 8,
  HOP_STANDING = 9,
  HOP_MOVING = 10,
  SIDE_JUMP = 11,
  TURN_JUMP = 12,
  NORMAL_TO_WHEELIE = 13,
  WHEELIE_TO_NORMAL = 14,
  WHEELIE_HOPPING_STANDING = 15,
  WHEELIE_HOPPING_MOVING = 16,
  WHEELIE_MOVING = 17,
  WHEELIE_RISING_MOVING = 18,
  WHEELIE_LOWERING_MOVING = 19,
}

export enum RejectionReason {
  NONE = 0,
  COLLISION = 1,
  OUT_OF_BOUNDS = 2,
  SEQUENCE_MISMATCH = 3,
  NOT_JOINED = 4,
  INVALID_DIRECTION = 5,
  FORCED_MOVEMENT_DISABLED = 6,
}

export enum PlayerAvatar {
  BRENDAN = 0,
  MAY = 1,
}

export type Position = { x: number; y: number };
export type JoinSession = { player_id: string };
export type WalkInput = {
  direction: Direction;
  movement_mode: MovementMode;
  held_buttons: number;
  input_seq: number;
  client_time: bigint;
};
export type HeldInputState = {
  held_direction?: Direction;
  held_buttons: number;
  input_seq: number;
  client_time: bigint;
};
export type DebugTraversalInput = {
  action: DebugTraversalAction;
};
export type PlayerActionInput = {
  action: PlayerAction;
};
export type SessionAccepted = { session_id: number; server_frame: number; avatar: PlayerAvatar };
export type WorldSnapshot = {
  map_id: number;
  player_pos: Position;
  facing: Direction;
  avatar: PlayerAvatar;
  map_chunk_hash: Uint8Array;
  map_chunk: Uint8Array;
  server_frame: number;
  traversal_state: TraversalState;
  preferred_bike_type: TraversalState;
  authoritative_step_speed?: StepSpeed;
  mach_speed_stage?: number;
  acro_substate?: AcroBikeSubstate;
  bike_transition?: BikeTransitionType;
  bike_effect_flags: number;
};
export type WalkResult = {
  input_seq: number;
  accepted: boolean;
  authoritative_pos: Position;
  facing: Direction;
  reason: RejectionReason;
  server_frame: number;
  traversal_state: TraversalState;
  preferred_bike_type: TraversalState;
  authoritative_step_speed?: StepSpeed;
  mach_speed_stage?: number;
  acro_substate?: AcroBikeSubstate;
  bike_transition?: BikeTransitionType;
  bike_effect_flags: number;
};
export type WorldDelta = { map_id: number; server_frame: number; delta_blob: Uint8Array };
